# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('logo', models.ImageField(default='/uploads/None/no-img.jpg', upload_to='static/uploads/')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='/uploads/None/no-img.jpg', upload_to='static/uploads/')),
                ('image', models.ImageField(default='/uploads/None/no-img.jpg', upload_to='static/uploads/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('help_text', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
                ('allowed_providers', models.CharField(default='vk,fb,ok,ig,tw', max_length=200, verbose_name='Allowed providers (Comma separate (vk,fb,ok,ig,tw))')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Guest')),
            ],
        ),
    ]
