# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='company',
        ),
    ]
