# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160803_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='sfsdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='/uploads/None/no-img.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='background',
            field=models.ImageField(default='/uploads/None/no-img.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='/uploads/None/no-img.jpg', upload_to='uploads/'),
        ),
    ]
