# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160804_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
