# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_promotion_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('website', models.CharField(default='', max_length=20)),
                ('key', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='promotion',
            name='Rules',
            field=models.CharField(blank=True, max_length=100, verbose_name='Select rules for customer segmentation'),
        ),
    ]
