# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160804_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network',
        ),
    ]
