# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='Rules',
        ),
        migrations.AddField(
            model_name='promotion',
            name='allowed_providers',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
