# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160804_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
