# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(),
        ),
    ]
