# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160804_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='/uploads/None/no-img.jpg', upload_to='app/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='background',
            field=models.ImageField(default='/uploads/None/no-img.jpg', upload_to='app/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='/uploads/None/no-img.jpg', upload_to='app/static/uploads/'),
        ),
    ]
